# -*- coding: utf-8 -*-
"""Data Creation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aHx32IdKD5Q2jB0AP44R3pMVOdUbWqLU
"""

import pandas as pd
import string

with open('raw_string.txt','r') as file:
  raw_string = file.read()

first_split = raw_string.splitlines()

for item in first_split:
  if len(item) <= 5:
    first_split.pop(first_split.index(item))


first_split[:20]

list_1 = []
for item in first_split:
  list_1.append(item.split(' '))

list_1[:10]

list_x = []

for item in list_1:
  x = item[0]
  y = item[1]
  z = item[-1]
  refined_item = [x, y, z]
  list_x.append(refined_item)

list_x[:5]

categories = ['nm', 'nf', 'v', 'adj', 'conj', 'adv', 'pron', 'num', 'nmf', 'prep', 'nm/f', 'nc', 'interj', 'av', 'art', 'aj', 'n']
for item in list_x:
  if item[1] not in categories:
    list_x.pop(list_x.index(item))
  if item[1] == 'num' or item[1] == 'pron':
    list_x.pop(list_x.index(item))
  if item[1] in ['nc', 'nf', 'nm', 'nm/f']:
    item[1] = 'noun'

list_x[:5]

for item in list_x:
  item.append(len(item[0]))

list_x[:5]

for item in list_x:
  if len(item) != 4:
    print(list_x.index(item))

special_characters = ['á',	'é',	'í',	'ñ',	'ó',	'ú',	'ü']

for thing in list_x:
  special_character_checker = False
  for character in special_characters:
    if character in thing[0]:
      special_character_checker = True
  thing.append(special_character_checker)

list_x[:5]

for item in list_x:
  if len(item) != 5:
    print(list_x.index(item))

#checkpoint

vowels_list = ['a', 'e', 'i', 'o', 'u']
alphabet = string.ascii_lowercase
consonants_list = []


for c in alphabet:
  if c in vowels_list:
    continue
  else:
    consonants_list.append(c)

for item in list_x:
  consonants = 0
  vowels = 0
  for i in range(len(item[0])):
    if item[0][i] in consonants_list:
      consonants += 1
    if item[0][i] in vowels_list:
      vowels += 1

  item.append(vowels)
  item.append(consonants)

list_x[:5]

for item in list_x:
  if len(item) != 7:
    print(list_x.index(item))

#checkpoint

# this is where the problem is:
for item in list_x:
  double_letters = False
  for i in range(len(item[0])):
    if i + 1 < len(item[0]) and item[0][i] == item[0][i+1]:
      double_letters = True
      continue

  item.append(double_letters)

list_x[:5]

for item in list_x:
  if len(item) != 8:
    print(list_x.index(item))

# checkpoint

for item in list_x:
  ends_with_vowel = False
  if item[0][-1] in vowels_list:
    ends_with_vowel = True

  item.append(ends_with_vowel)

list_x[:5]

for item in list_x:
  if len(item) != 9:
    print(list_x.index(item))

# for each word, counting the occurence of the most frequently
# used letters in the spanish language.
# source for frequency of letters
# --> https://www.sttmedia.com/characterfrequency-spanish

for item in list_x:
  e = 0
  a = 0
  o = 0
  s = 0
  for i in range(len(item[0])):
    if item[0][i] == 'e':
      e += 1
    if item[0][i] == 'a':
      a += 1
    if item[0][i] == 'o':
      o += 1
    if item[0][i] == 's':
      s += 1

  item.append(e)
  item.append(a)
  item.append(o)
  item.append(s)

for item in list_x:
  if len(item) != 13:
    print(list_x.index(item))

word = []
part_of_speech = []
frequency_rating = []
word_length = []
contains_special_characters = []
num_vowels = []
num_consonants = []
sequential_letters = []
vowel_ending = []
e_freq = []
a_freq = []
o_freq = []
s_freq = []

for item in list_x:
  word.append(item[0])
  part_of_speech.append(item[1])
  frequency_rating.append(item[2])
  word_length.append(item[3])
  contains_special_characters.append(item[4])
  num_vowels.append(item[5])
  num_consonants.append(item[6])
  sequential_letters.append(item[7])
  vowel_ending.append(item[8])
  e_freq.append(item[9])
  a_freq.append(item[10])
  o_freq.append(item[11])
  s_freq.append(item[12])

print(len(word))
print(len(part_of_speech))
print(len(frequency_rating))
print(len(word_length))
print(len(contains_special_characters))
print(len(num_vowels))
print(len(num_consonants))
print(len(sequential_letters))
print(len(vowel_ending))
print(len(e_freq))
print(len(a_freq))
print(len(o_freq))
print(len(s_freq))

df_spanish = pd.DataFrame()

df_spanish['Raw word'] = word
df_spanish['Part of Speech'] = part_of_speech
df_spanish['frequency score'] = frequency_rating
df_spanish['Word length'] = word_length
df_spanish['Contains special characters?'] = contains_special_characters
df_spanish['# of vowels'] = num_vowels
df_spanish['# of consonants'] = num_consonants
df_spanish['Contains repeated sequential characters?'] = sequential_letters
df_spanish['Ends with a vowel?'] = vowel_ending
df_spanish['e count'] = e_freq
df_spanish['a count'] = a_freq
df_spanish['o count'] = o_freq
df_spanish['s count'] = s_freq

df_spanish
